/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.licitat.hiberplay;

import com.google.common.base.Supplier;
import com.google.common.base.Suppliers;
import io.licitat.hiberplay.plays.RtPlanAdventures;
import io.licitat.hiberplay.plays.SaveLinkAndDelete;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class App {

    private static Supplier<EntityManagerFactory> factorySupplier = Suppliers.memoize(
        () -> Persistence.createEntityManagerFactory("my-persistence-unit")
    );

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        /*
        System.out.println(new App().getGreeting());

        Post thePost = doInJPA(App::createEMF, em -> {
            Post aPost = new Post("This is a post");
            em.persist(aPost);
            return aPost;
        });

        System.out.println(thePost.getId());
        */

        /*
        doInJPA(App::createEMF, em -> {
            Post aPost = new Post("This is a second post");
            Tag aNewTag = new Tag("First tag");

            aPost.addTag(aNewTag);

            em.persist(aPost);
            return aPost;
        });
        */

        //new SaveLinkAndDelete(factorySupplier).run();
        //new MaaaaaanyRecords(factorySupplier).run();
        new RtPlanAdventures(factorySupplier).run();
    }


    @Deprecated
    private static EntityManagerFactory createEMF() {
        return Persistence.createEntityManagerFactory("my-persistence-unit");
    }
}
